### PR TITLE
175 update rust edition

### LINKED ISSUE #175: Update rust-edition

### PR DESCRIPTION
**Pull request by idruzhitskiy**
Closes #175

### CODE REVIEW

**Comment by ikopylov** [comment]
@idruzhitskiy GitHub in `File changed` tab prints a lot of warnings about `no-run` (`unknown attribute 'no-run'. Did you mean 'no_run'?`). I see, that it is being used to denote code sections in doc comments, and `no-run` in this case is actually unsupported value. Can you replace all these `no-run` to `rust` as a part of this PR?

**Comment by idruzhitskiy** [comment]
> @idruzhitskiy GitHub in `File changed` tab prints a lot of warnings about `no-run` (`unknown attribute 'no-run'. Did you mean 'no_run'?`). I see, that it is being used to denote code sections in doc comments, and `no-run` in this case is actually unsupported value. Can you replace all these `no-run` to `rust` as a part of this PR?

I tried to replace them and it lead to more errors during `cargo doc` due to outdated doc exampless. The same warnings are in the master branch too. Should I actualize doc examples here or in the separate request?

**Comment by ikopylov** [comment]
> Should I actualize doc examples here or in the separate request?
In this case, it is better to do it in a separate request

**Review by ikopylov — APPROVED** [review]
LGTM

**Pull request merged**
